service: notifier # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  environment:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/MYROOM_URL
    URL: ${env:APP_URL}

functions:
  slack:
    handler: handlerapi.post_to_slack
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ecs"
            detail-type:
              - "ECS Task State Change"
            detail:
              clusterArn:
                - ${env:APP_URL}

plugins:
  - serverless-python-requirements
